wandb_version: 1

learning_rate:
  desc: null
  value: 1.0
architecture:
  desc: null
  value: CNN
dataset:
  desc: null
  value: MNIST
epochs:
  desc: null
  value: 2
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709737825.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      - 24
      4: 3.8.10
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
