wandb_version: 1

learning_rate:
  desc: null
  value: 0.006082141425218532
epochs:
  desc: null
  value: 3
gamma:
  desc: null
  value: 0.38386994985693057
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709743525.0
    t:
      1:
      - 1
      - 35
      - 41
      - 55
      2:
      - 1
      - 35
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
