wandb_version: 1

learning_rate:
  desc: null
  value: 0.0026403217107623528
epochs:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.26270222560852796
_wandb:
  desc: null
  value:
    python_version: 3.8.10
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1709743799.0
    t:
      1:
      - 1
      - 35
      - 41
      - 55
      2:
      - 1
      - 35
      - 41
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.8.10
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
